Repository yiisoft/data, pull requests merged in 2024-09, with the labels that each got.

#188 Wording fixes
  CHANGELOG.md
  README.md
  src/Paginator/KeysetPaginator.php
  src/Paginator/OffsetPaginator.php
  src/Paginator/PaginatorInterface.php
  src/Processor/DataProcessorInterface.php
  src/Reader/Filter/Between.php
  src/Reader/FilterHandlerInterface.php
  src/Reader/FilterableDataInterface.php
  src/Reader/Iterable/FilterHandler/EqualsHandler.php
  src/Reader/Iterable/IterableDataReader.php
  src/Reader/LimitableDataInterface.php
  src/Reader/OffsetableDataInterface.php
  src/Reader/OrderHelper.php
  src/Reader/ReadableDataInterface.php
  src/Reader/Sort.php
  src/Reader/SortableDataInterface.php
  src/Writer/WriteableInterface.php
Labels: type:docs

#189 Fix #182: Add note about keys
  src/Reader/ReadableDataInterface.php
Labels: type:docs

#190 Fix #175: Add testcase for multibyte LikeHandler
  CHANGELOG.md
  src/Reader/Iterable/FilterHandler/LikeHandler.php
  tests/Reader/Iterable/FilterHandler/LikeHandlerTest.php
Labels: type:enhancement

#195 Fix invalid count in `IterableDataReader` when limit or/and offset used
  CHANGELOG.md
  src/Reader/Iterable/IterableDataReader.php
  tests/Reader/Iterable/IterableDataReaderTest.php
Labels: status:code review

#194 Improve psalm annotations in `LimitableDataInterface`
  CHANGELOG.md
  src/Paginator/KeysetPaginator.php
  src/Paginator/OffsetPaginator.php
  src/Reader/Iterable/IterableDataReader.php
  src/Reader/LimitableDataInterface.php
Labels: status:code review

#196 Taken into account data reader limit in `OffsetPaginator::getTotalItems()`
  CHANGELOG.md
  infection.json.dist
  src/Paginator/OffsetPaginator.php
  tests/Paginator/OffsetPaginatorTest.php
Labels: status:code review

#199 Fix typo
  src/Reader/LimitableDataInterface.php
Labels: type:task
